config_version = 14

[accessibility]
ui_scale = 0.95000000670552254

[bar.default]
border = "secondary"
border_width = 1.0
center = [ "workspaces" ]
concave_edge_corners = false
font_scale = 1.0499999839812517
margin_edge = 2
margin_ends = 2
padding = 20
radius = 0
reserve_space = false
start = [ "launcher", "clock", "cpu", "wallpaper", "taskbar" ]
thickness = 30
widget_spacing = 10

[dock]
reserve_space = false

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@HDMI-A-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "HDMI-A-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[shell.animation]
speed = 1.5000000223517418

[shell.screenshot]
confirm_region = true
remember_last_region = true
show_cursor = true

[theme]
builtin = "Noctalia"
community_palette = "Oxocarbon"
mode = "dark"
source = "builtin"
wallpaper_scheme = "m3-content"

[wallpaper]
directory = "/home/franco/wallpapers"

    [wallpaper.automation]
    enabled = true

    [wallpaper.default]
    path = "/home/franco/wallpapers/cachyos/Skyscraper.png"

    [wallpaper.last]
    path = "/home/franco/wallpapers/cachyos/Skyscraper.png"

    [wallpaper.monitors.HDMI-A-1]
    path = "/home/franco/wallpapers/cachyos/Skyscraper.png"

[widget.battery]
enabled = false

[widget.bluetooth]
enabled = false

[widget.brightness]
enabled = false

[widget.clipboard]
enabled = false

[widget.network]
show_label = false

[widget.wallpaper]
enabled = false